/**
 * Generate the full HTML page for the plan viewer window.
 * Self-contained page with all CSS/JS inlined.
 */

function escapeHtml(text: string): string {
  return String(text)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

export function generatePlanViewerHTML(opts: {
  markdown: string;
  title: string;
  feature: string;
  port: number;
}): string {
  const { markdown, title, feature, port } = opts;

  // Build safe state for JavaScript
  const escapedMarkdown = markdown.replace(/<\//g, "<\\/").replace(/\\/g, "\\\\");
  const escapedTitle = escapeHtml(title);

  return [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '<title>' + escapedTitle + ' — Plan Viewer</title>',
    '<style>',
    ':root {',
    '  --bg: #1a1d23;',
    '  --surface: #1e2228;',
    '  --surface2: #252a32;',
    '  --border: #2e343e;',
    '  --text: #e2e8f0;',
    '  --text-muted: #8892a0;',
    '  --text-dim: #555d6e;',
    '  --accent: #58a6ff;',
    '  --accent-hover: #3a9ad5;',
    '  --accent-dim: rgba(88, 166, 255, 0.12);',
    '  --success: #48d889;',
    '  --success-bg: rgba(72, 216, 137, 0.08);',
    '  --warning: #f0b429;',
    '  --error: #e85858;',
    '  --font: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, sans-serif;',
    '  --mono: "SF Mono", "Fira Code", "JetBrains Mono", Consolas, monospace;',
    '}',
    '',
    '* { box-sizing: border-box; margin: 0; padding: 0; }',
    'html { height: 100%; }',
    'body {',
    '  background: var(--bg);',
    '  color: var(--text);',
    '  font-family: var(--font);',
    '  font-size: 15px;',
    '  line-height: 1.65;',
    '  height: 100%;',
    '  display: flex;',
    '  flex-direction: column;',
    '  overflow: hidden;',
    '}',
    '',
    '.header {',
    '  background: var(--surface);',
    '  border: 1px solid var(--border);',
    '  border-left: 3px solid var(--accent);',
    '  border-radius: 6px;',
    '  margin: 12px 16px 0;',
    '  padding: 14px 20px;',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 14px;',
    '  position: sticky;',
    '  top: 12px;',
    '  z-index: 100;',
    '}',
    '',
    '.header .badge {',
    '  background: transparent;',
    '  color: var(--accent);',
    '  font-size: 11px;',
    '  font-weight: 700;',
    '  padding: 3px 10px;',
    '  border: 1px solid var(--accent);',
    '  border-radius: 4px;',
    '  text-transform: uppercase;',
    '  letter-spacing: 1px;',
    '  font-family: var(--mono);',
    '}',
    '',
    '.header .title {',
    '  font-size: 15px;',
    '  font-weight: 600;',
    '  color: var(--text);',
    '  flex: 1;',
    '}',
    '',
    '.header .meta {',
    '  font-size: 12px;',
    '  font-family: var(--mono);',
    '  color: var(--text-muted);',
    '}',
    '',
    '.header .modified-badge {',
    '  font-size: 10px;',
    '  font-family: var(--mono);',
    '  font-weight: 600;',
    '  color: var(--warning);',
    '  border: 1px solid var(--warning);',
    '  padding: 2px 8px;',
    '  border-radius: 4px;',
    '  display: none;',
    '}',
    '',
    '.header .modified-badge.visible { display: inline-block; }',
    '',
    '.toolbar {',
    '  display: flex;',
    '  gap: 6px;',
    '  margin: 10px 16px 0;',
    '}',
    '',
    '.toolbar button {',
    '  background: var(--surface);',
    '  color: var(--text-muted);',
    '  border: 1px solid var(--border);',
    '  border-radius: 6px;',
    '  padding: 8px 14px;',
    '  font-size: 13px;',
    '  font-family: var(--font);',
    '  cursor: pointer;',
    '  transition: all 0.15s;',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 6px;',
    '}',
    '',
    '.toolbar button:hover {',
    '  background: var(--surface2);',
    '  color: var(--text);',
    '  border-color: var(--accent);',
    '}',
    '',
    '.toolbar button.active {',
    '  background: var(--accent-dim);',
    '  color: var(--accent);',
    '  border-color: var(--accent);',
    '}',
    '',
    '.toolbar button.primary {',
    '  background: var(--accent);',
    '  color: #fff;',
    '  border-color: var(--accent);',
    '}',
    '',
    '.toolbar button.primary:hover { background: var(--accent-hover); }',
    '',
    '.content {',
    '  flex: 1;',
    '  overflow-y: auto;',
    '  margin: 12px 16px 16px;',
    '  background: var(--surface);',
    '  border: 1px solid var(--border);',
    '  border-radius: 8px;',
    '  padding: 20px 24px;',
    '}',
    '',
    '.plan-container { max-width: 800px; margin: 0 auto; }',
    '',
    '.plan-item {',
    '  display: flex;',
    '  align-items: flex-start;',
    '  gap: 10px;',
    '  padding: 8px 12px;',
    '  border-radius: 6px;',
    '  margin-bottom: 4px;',
    '  transition: background 0.12s;',
    '}',
    '',
    '.plan-item:hover { background: var(--surface2); }',
    '',
    '.plan-item h1, .plan-item h2, .plan-item h3 {',
    '  color: var(--text);',
    '  margin: 16px 0 12px;',
    '}',
    '',
    '.plan-item h1:first-child, .plan-item h2:first-child { margin-top: 0; }',
    '',
    '.plan-item .checkbox {',
    '  width: 18px;',
    '  height: 18px;',
    '  border: 2px solid var(--border);',
    '  border-radius: 4px;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  cursor: pointer;',
    '  flex-shrink: 0;',
    '  margin-top: 2px;',
    '  transition: all 0.15s;',
    '}',
    '',
    '.plan-item .checkbox.checked {',
    '  background: var(--success);',
    '  border-color: var(--success);',
    '  color: #fff;',
    '}',
    '',
    '.plan-item .checkbox:hover { border-color: var(--accent); }',
    '',
    '.plan-item .text { flex: 1; color: var(--text); }',
    '.plan-item .text.checked {',
    '  color: var(--text-dim);',
    '  text-decoration: line-through;',
    '}',
    '',
    '.plan-item .bullet {',
    '  color: var(--accent);',
    '  font-weight: 700;',
    '  flex-shrink: 0;',
    '}',
    '',
    '.plan-item .numbered {',
    '  color: var(--accent);',
    '  font-weight: 700;',
    '  min-width: 24px;',
    '  flex-shrink: 0;',
    '}',
    '',
    '.footer {',
    '  background: var(--surface);',
    '  border-top: 1px solid var(--border);',
    '  padding: 14px 20px;',
    '  display: flex;',
    '  justify-content: space-between;',
    '  align-items: center;',
    '  gap: 16px;',
    '}',
    '',
    '.footer .hint {',
    '  font-size: 12px;',
    '  color: var(--text-muted);',
    '  font-family: var(--mono);',
    '}',
    '',
    '.footer .actions { display: flex; gap: 10px; }',
    '',
    '.footer button {',
    '  padding: 10px 20px;',
    '  border-radius: 8px;',
    '  font-size: 14px;',
    '  font-weight: 600;',
    '  cursor: pointer;',
    '  transition: all 0.15s;',
    '  border: none;',
    '}',
    '',
    '.footer button.approve { background: var(--success); color: #fff; }',
    '.footer button.approve:hover { background: #3ac77a; }',
    '.footer button.needs-fix { background: var(--warning); color: #000; }',
    '.footer button.needs-fix:hover { background: #e5a820; }',
    '.footer button.close {',
    '  background: transparent;',
    '  color: var(--text-muted);',
    '  border: 1px solid var(--border);',
    '}',
    '.footer button.close:hover { background: var(--surface2); color: var(--text); }',
    '',
    '@keyframes fadeIn {',
    '  from { opacity: 0; transform: translateY(-8px); }',
    '  to { opacity: 1; transform: translateY(0); }',
    '}',
    '',
    '.content { animation: fadeIn 0.2s ease-out; }',
    '</style>',
    '</head>',
    '<body>',
    '<div class="header">',
    '  <span class="badge">PLAN</span>',
    '  <span class="title" id="planTitle">' + escapedTitle + '</span>',
    '  <span class="meta" id="featureName">' + escapeHtml(feature) + '</span>',
    '  <span class="modified-badge" id="modifiedBadge">MODIFIED</span>',
    '</div>',
    '',
    '<div class="toolbar" id="toolbar">',
    '  <button id="btnApprove" class="primary" onclick="approvePlan()">Approve Plan</button>',
    '  <button id="btnNeedsFix" onclick="needsFix()">Needs Fix</button>',
    '  <button id="btnRefresh" onclick="refreshPlan()">Refresh</button>',
    '</div>',
    '',
    '<div class="content" id="content">',
    '  <div class="plan-container" id="planContainer"></div>',
    '</div>',
    '',
    '<div class="footer">',
    '  <span class="hint">Click checkboxes to mark complete</span>',
    '  <div class="actions">',
    '    <button class="close" onclick="closeViewer()">Close</button>',
    '  </div>',
    '</div>',
    '',
    '<script>',
    'var state = { markdown: ' + JSON.stringify(markdown) + ', title: ' + JSON.stringify(title) + ', feature: "' + feature + '", port: ' + port + ' };',
    'var currentMarkdown = state.markdown;',
    '',
    'function escapeHtml(text) {',
    '  return String(text)',
    '    .replace(/&/g, "&amp;")',
    '    .replace(/</g, "&lt;")',
    '    .replace(/>/g, "&gt;");',
    '}',
    '',
    'function parsePlan(md) {',
    '  var lines = md.split("\\n");',
    '  var items = [];',
    '  var inCode = false;',
    '',
    '  for (var i = 0; i < lines.length; i++) {',
    '    var line = lines[i];',
    '    if (line.startsWith("```")) {',
    '      inCode = !inCode;',
    '      items.push({ kind: "code", text: line });',
    '      continue;',
    '    }',
    '    if (inCode) {',
    '      items.push({ kind: "code", text: line });',
    '      continue;',
    '    }',
    '',
    '    var cbMatch = line.match(/^(\\s*)- \\[([ xX])\\] (.+)$/);',
    '    if (cbMatch) {',
    '      items.push({',
    '        kind: "checkbox",',
    '        indent: cbMatch[1].length,',
    '        checked: cbMatch[2].toLowerCase() === "x",',
    '        text: cbMatch[3]',
    '      });',
    '      continue;',
    '    }',
    '',
    '    var headingMatch = line.match(/^(#{1,6}) (.+)$/);',
    '    if (headingMatch) {',
    '      items.push({',
    '        kind: "heading",',
    '        level: headingMatch[1].length,',
    '        text: headingMatch[2]',
    '      });',
    '      continue;',
    '    }',
    '',
    '    var numMatch = line.match(/^(\\s*)(\\d+)[.)] (.+)$/);',
    '    if (numMatch) {',
    '      items.push({',
    '        kind: "numbered",',
    '        indent: numMatch[1].length,',
    '        number: numMatch[2],',
    '        text: numMatch[3]',
    '      });',
    '      continue;',
    '    }',
    '',
    '    var bulletMatch = line.match(/^(\\s*)[-*+] (.+)$/);',
    '    if (bulletMatch) {',
    '      items.push({',
    '        kind: "bullet",',
    '        indent: bulletMatch[1].length,',
    '        text: bulletMatch[2]',
    '      });',
    '      continue;',
    '    }',
    '',
    '    if (line.trim()) {',
    '      items.push({ kind: "text", indent: 0, text: line.trim() });',
    '    }',
    '  }',
    '',
    '  return items;',
    '}',
    '',
    'function renderPlan() {',
    '  var items = parsePlan(currentMarkdown);',
    '  var container = document.getElementById("planContainer");',
    '  var html = "<div class=\\"plan-container\\">";',
    '',
    '  for (var i = 0; i < items.length; i++) {',
    '    var item = items[i];',
    '    if (item.kind === "heading") {',
    '      html += "<div class=\\"plan-item\\"><h" + item.level + ">" + escapeHtml(item.text) + "</h" + item.level + "></div>";',
    '    } else if (item.kind === "checkbox") {',
    '      var cls = item.checked ? "checked" : "";',
    '      html += "<div class=\\"plan-item\\"><div class=\\"checkbox " + cls + "\\" onclick=\\"toggleCheckbox(this)\\">" +',
    '        (item.checked ? "&#10003;" : "") + "</div>" +',
    '        "<span class=\\"text " + cls + "\\">" + escapeHtml(item.text) + "</span></div>";',
    '    } else if (item.kind === "bullet") {',
    '      html += "<div class=\\"plan-item\\"><span class=\\"bullet\\">&#8226;</span><span class=\\"text\\">" + escapeHtml(item.text) + "</span></div>";',
    '    } else if (item.kind === "numbered") {',
    '      html += "<div class=\\"plan-item\\"><span class=\\"numbered\\">" + item.number + ".</span><span class=\\"text\\">" + escapeHtml(item.text) + "</span></div>";',
    '    } else if (item.kind === "code") {',
    '      html += "<pre><code>" + escapeHtml(item.text) + "</code></pre>";',
    '    } else {',
    '      html += "<div class=\\"plan-item\\"><span class=\\"text\\">" + escapeHtml(item.text) + "</span></div>";',
    '    }',
    '  }',
    '',
    '  html += "</div>";',
    '  container.innerHTML = html;',
    '}',
    '',
    'function toggleCheckbox(el) {',
    '  el.classList.toggle("checked");',
    '  el.innerHTML = el.classList.contains("checked") ? "&#10003;" : "";',
    '  el.closest(".plan-item").querySelector(".text").classList.toggle("checked");',
    '  state.modified = true;',
    '  document.getElementById("modifiedBadge").classList.add("visible");',
    '}',
    '',
    'function approvePlan() {',
    '  fetch("http://localhost:" + state.port + "/action", {',
    '    method: "POST",',
    '    headers: { "Content-Type": "application/json" },',
    '    body: JSON.stringify({ action: "approve", markdown: currentMarkdown })',
    '  }).then(function() { window.close(); });',
    '}',
    '',
    'function needsFix() {',
    '  var comment = prompt("What needs to be fixed?") || "";',
    '  fetch("http://localhost:" + state.port + "/action", {',
    '    method: "POST",',
    '    headers: { "Content-Type": "application/json" },',
    '    body: JSON.stringify({ action: "needs_fix", markdown: currentMarkdown, comment: comment })',
    '  }).then(function() { window.close(); });',
    '}',
    '',
    'function refreshPlan() {',
    '  fetch("http://localhost:" + state.port + "/markdown")',
    '    .then(function(r) { return r.json(); })',
    '    .then(function(data) {',
    '      currentMarkdown = data.markdown;',
    '      renderPlan();',
    '    });',
    '}',
    '',
    'function closeViewer() { window.close(); }',
    '',
    'renderPlan();',
    '</script>',
    '</body>',
    '</html>',
  ].join("\n");
}
